### ISSUE TITLE
To-do list:

### ISSUE THREAD

**Issue by digital-nomad8620** [AlexanderJDupree/text_adventure_game#7]
1: We need to create a victory sequence that plays out.

2: Finish making death scenarios and implement them

3: Populate game_start.txt with room descriptions, items, and enemies. each room should have at least 3 descriptions. The first will be the initial room description, the second will be the re-entry description and the 3rd will be the examine room only description. The examine room description should highlight any special actions and items in the room

That's all I can think of off the top of my head!  Comment to add to the to-do list.

**Comment by jake-bickle** [comment]
4. Fully implement beartrap. It's a one time use item that can be used on any enemy to do massive amount of damage. It's to help with the bear fight mainly but player can use it on wolf and rat too if they so please.

**Comment by jake-bickle** [comment]
5. Completely update "help" function to truly represent all possible options.

**Comment by jake-bickle** [comment]
6. Examine room is as well as items(?)

**Comment by AlexanderJDupree** [comment]
6, you can examine room. The last description for each room in the text file should be reserved for the room examination description. And it should highlight items and room branches.

**Comment by AlexanderJDupree** [comment]
In the current version I just updated the help function to reflect all possible actions at the moment.

**Comment by jake-bickle** [comment]
Implement crying during combat. If you do, you lose your dignity and maybe this alters the ending? I can add it to the game, not tonight though cause I'm tired lol
Petting the wolf in the tunnel isn't implemented. We could get rid of this if we wanted to.

**Comment by jake-bickle** [comment]
I want to see if I can get the save system working as well.

**Comment by jake-bickle** [comment]
Fix gun.
Add an equip feature during combat. If I have a gun with no bullets, I'm screwed unless I run.
